
package tfc;

import com.jtattoo.plaf.noire.NoireLookAndFeel;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.ConsoleHandler;
import java.util.logging.FileHandler;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author terak
 */
public class Aniadir extends javax.swing.JFrame {

    /**
     * Creates new form AniadirPlanta
     */
    private HashMap<String, Integer> idtipo = new HashMap<String, Integer>();
    private HashMap<String, Integer> idmarca = new HashMap<String, Integer>();
    private HashMap<String, Integer> idusuario = new HashMap<String, Integer>();
    public Aniadir() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setResizable(true);
         Statement sentencia;
        try {
            sentencia = dameConexion().createStatement();
            String sql = "SELECT id_dispositivo FROM Dispositivo;";
            ResultSet resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBoxIdDispositivo.addItem(resul.getString(1));
            }
            sql = "SELECT id_puesto FROM Puesto;";
            resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBoxIdPuesto.addItem(resul.getString(1));
            }
            sql = "SELECT P.id_puesto FROM Puesto P WHERE NOT EXISTS (SELECT 1 FROM Usuario_Puesto UP WHERE UP.id_puesto = P.id_puesto);";
            resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBoxIdPuestoUsuario.addItem(resul.getString(1));
            }
            
            sql = "SELECT U.id_usuario, U.usuario FROM Usuario U ORDER BY U.id_usuario;";
            resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBoxIdUsuario.addItem(resul.getString(2));
                //System.out.print(resul.getString(2));
                idusuario.put(resul.getString(2),resul.getInt(1));
            }
            
            
            sql = "SELECT id_tipo,tipo FROM Tipo;";
            resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBoxTipo.addItem(resul.getString(2));
                idtipo.put(resul.getString(2), resul.getInt(1));
            }
            sql = "SELECT id_marca, marca FROM Marca;";
            resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBoxMarca.addItem(resul.getString(2));
                idmarca.put(resul.getString(2), resul.getInt(1));
            }
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        
    }
    private FileHandler fileHandler;
    private ConsoleHandler cons;
    private Logger log = Logger.getLogger("controlador");
    private void logs(){
    try {
            cons = new ConsoleHandler();
            log.addHandler(cons);
            fileHandler = new FileHandler("Logs/errorres.log", true);
            fileHandler.setFormatter(new SimpleFormatter());
            log.addHandler(fileHandler);
        } catch (IOException e) {
            e.printStackTrace();
            log.severe("Ocurrió un error: " + e.getMessage());
        }
    }
     private Connection dameConexion(){
        Connection con = null;
        String baseDatos = "jdbc:sqlite:"+System.getProperty("user.dir")+"\\BBDD\\BBDD.db";
        
        /*File f = new File(System.getProperty("user.dir")+"\\BBDD\\BBDD.db");
        System.out.println(f.exists());*/
        try {
            con= DriverManager.getConnection(baseDatos);
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        return con;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonasignar = new javax.swing.JButton();
        jComboBoxIdDispositivo = new javax.swing.JComboBox<>();
        jComboBoxIdPuesto = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldApellido1 = new javax.swing.JTextField();
        jTextFieldApellido2 = new javax.swing.JTextField();
        jButtonUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxMarca = new javax.swing.JComboBox<>();
        jTextFieldIdDispositivo = new javax.swing.JTextField();
        jTextFieldModelo = new javax.swing.JTextField();
        jTextFieldNumeroDeSerie = new javax.swing.JTextField();
        jTextFieldIp = new javax.swing.JTextField();
        jTextFieldMac = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButtonDispositivos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jFormattedTextFieldean13 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldIdPuesto1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldPlanta1 = new javax.swing.JTextField();
        jButtonaniadirPuesto = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonasignar1 = new javax.swing.JButton();
        jComboBoxIdUsuario = new javax.swing.JComboBox<>();
        jComboBoxIdPuestoUsuario = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAniadirPlanta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar puesto a dispositivo"));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Id_puesto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Id_dispositivos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel1.add(jLabel3, gridBagConstraints);

        jButtonasignar.setText("Añadir");
        jButtonasignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonasignarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jButtonasignar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel1.add(jComboBoxIdDispositivo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel1.add(jComboBoxIdPuesto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 34;
        gridBagConstraints.insets = new java.awt.Insets(0, 35, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel4.setText("Usuario*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jTextFieldUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jTextFieldNombre, gridBagConstraints);

        jLabel5.setText("Nombre*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Primer apellido*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Segundo apellido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jLabel7, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jTextFieldApellido1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 6);
        jPanel2.add(jTextFieldApellido2, gridBagConstraints);

        jButtonUsuario.setText("Añadir usuario");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 21, 0, 0);
        jPanel2.add(jButtonUsuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 72;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(30, 21, 10, 0);
        getContentPane().add(jPanel2, gridBagConstraints);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dispositivo"));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo del dispositivo*" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jComboBoxTipo, gridBagConstraints);

        jComboBoxMarca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca*" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jComboBoxMarca, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jTextFieldIdDispositivo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jTextFieldModelo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jTextFieldNumeroDeSerie, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jTextFieldIp, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jTextFieldMac, gridBagConstraints);

        jLabel9.setText("Id del dispositivo*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Modelo*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jLabel10, gridBagConstraints);

        jLabel11.setText("Numero de serie*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jLabel11, gridBagConstraints);

        jLabel12.setText("EAN13*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jLabel12, gridBagConstraints);

        jLabel13.setText("IP (Si tiene)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jLabel13, gridBagConstraints);

        jLabel14.setText("MAC (Si tiene)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jLabel14, gridBagConstraints);

        jButtonDispositivos.setText("Añadir");
        jButtonDispositivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDispositivosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        jPanel3.add(jButtonDispositivos, gridBagConstraints);

        jButton1.setText("Añadir tipo de dispositivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 8;
        jPanel3.add(jButton1, gridBagConstraints);

        jButton2.setText("Añadir marca");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        jPanel3.add(jButton2, gridBagConstraints);

        jFormattedTextFieldean13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldean13KeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        jPanel3.add(jFormattedTextFieldean13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 22;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(4, 40, 30, 26);
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Puesto"));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel15.setText("Id_puesto*");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel4.add(jLabel15, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel4.add(jTextFieldIdPuesto1, gridBagConstraints);

        jLabel16.setText("Planta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel4.add(jLabel16, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel4.add(jTextFieldPlanta1, gridBagConstraints);

        jButtonaniadirPuesto.setText("Añadir");
        jButtonaniadirPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaniadirPuestoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPanel4.add(jButtonaniadirPuesto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 21;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 140, 150);
        getContentPane().add(jPanel4, gridBagConstraints);

        jButton3.setText("Refrescar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jButton3, gridBagConstraints);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignar puesto vacio a usuario"));
        jPanel5.setLayout(new java.awt.GridBagLayout());

        jLabel8.setText("Id_puesto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel5.add(jLabel8, gridBagConstraints);

        jLabel17.setText("Id_usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel5.add(jLabel17, gridBagConstraints);

        jButtonasignar1.setText("Añadir");
        jButtonasignar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonasignar1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPanel5.add(jButtonasignar1, gridBagConstraints);

        jComboBoxIdUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Usuario--" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel5.add(jComboBoxIdUsuario, gridBagConstraints);

        jComboBoxIdPuestoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Puestos vacios--" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 120;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 15, 6);
        jPanel5.add(jComboBoxIdPuestoUsuario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.ipady = 34;
        getContentPane().add(jPanel5, gridBagConstraints);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Secciones");

        jMenuItem2.setText("Ventana Principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Dispositivos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Añadir");

        jMenuItemAniadirPlanta.setText("Añadir ");
        jMenuItemAniadirPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAniadirPlantaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAniadirPlanta);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Info");

        jMenuItem1.setText("Acerca De");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        VentanaPrincipal v1 = new VentanaPrincipal();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal v1 = new VentanaPrincipal();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Usuarios v1 = new Usuarios();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Dispositivos v1 = new Dispositivos();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemAniadirPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAniadirPlantaActionPerformed
        // TODO add your handling code here:
        Aniadir v1 = new Aniadir();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAniadirPlantaActionPerformed

    private void jButtonasignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonasignarActionPerformed
       try{
            Statement sentencia = dameConexion().createStatement();
            String sql;
                
            sql="INSERT INTO Puesto_Dispositivo (id_puesto, id_dispositivo) VALUES("+jComboBoxIdPuesto.getSelectedItem().toString()+", "+jComboBoxIdDispositivo.getSelectedItem().toString()+" )";
            sentencia.executeUpdate(sql);
                
         } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this,"Has insertado datos incorrectos");
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
             JOptionPane.showMessageDialog(this,"Ha ocurrido un problema");
        }
    }//GEN-LAST:event_jButtonasignarActionPerformed
    private boolean validadorEan13(String doceEan)
    {
         int[] digitosEan = new int[12];
         int control=Character.getNumericValue(doceEan.charAt(12));
         for(int i =0;i<12;i++)
         {
             digitosEan[i]=Character.getNumericValue(doceEan.charAt(i));
         }
         int[] ean13 =
         {
            1, 3
         };
         int suma = 0;
         for(int i = 0; i < digitosEan.length; i++)
         {
             suma +=digitosEan[i] * ean13[i % 2];
         }
         int checksum = 10 - suma % 10;
         if(checksum == 10){
             checksum = 0;
         }
         boolean validador;
         validador = checksum == control;

         return validador;
    }
    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        try {
            // TODO add your handling code here:
           if(!jTextFieldUsuario.getText().isEmpty()&&!jTextFieldNombre.getText().isEmpty()&&!jTextFieldApellido1.getText().isEmpty())
                {Statement sentencia = dameConexion().createStatement();
                String sql;
                if(jTextFieldApellido2.getText().isEmpty()){
                    sql="INSERT INTO Usuario (usuario, nombre, apellido1) VALUES('"+jTextFieldUsuario.getText()+"', '"+jTextFieldNombre.getText()+"', '"+jTextFieldApellido1.getText()+"')";
                    //System.out.println(sql);
                    System.out.println(sentencia.executeUpdate(sql));
                }else{
                    sql="INSERT INTO Usuario (usuario, nombre, apellido1, apellido2) VALUES('"+jTextFieldUsuario.getText()+"', '"+jTextFieldNombre.getText()+"', '"+jTextFieldApellido1.getText()+"', '"+jTextFieldApellido2.getText()+"' )";
                    System.out.println(sql);
                    sentencia.executeUpdate(sql);
                }
                
            }else{
               JOptionPane.showMessageDialog(this, "Los campos con * son obligatorios");
           }   
       } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this,"Has insertado datos incorrectos");
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
             JOptionPane.showMessageDialog(this,"Ha ocurrido un problema");
        }
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    private void jButtonaniadirPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaniadirPuestoActionPerformed
        try {
            if(!jTextFieldIdPuesto1.getText().isEmpty()){
            // TODO add your handling code here:
            Statement sentencia = dameConexion().createStatement();
             String sql="INSERT INTO Puesto (id_puesto, planta) VALUES("+jTextFieldIdPuesto1.getText()+", "+jTextFieldPlanta1.getText()+")";
           // System.out.println(sql); 
            sentencia.executeUpdate(sql);
            }else{
            JOptionPane.showMessageDialog(this, "Los campos con * son obligatorios");
            }
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this,"Has insertado datos incorrectos");
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
             JOptionPane.showMessageDialog(this,"Ha ocurrido un problema");
        }
    }//GEN-LAST:event_jButtonaniadirPuestoActionPerformed

    private void jButtonDispositivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDispositivosActionPerformed
        // TODO add your handling code here:
         try {
             if(!jTextFieldIdDispositivo.getText().isEmpty()&&!jTextFieldModelo.getText().isEmpty()&&!jTextFieldNumeroDeSerie.getText().isEmpty()&&jComboBoxMarca.getSelectedIndex()!=0&&!jFormattedTextFieldean13.getText().isEmpty()&&jComboBoxTipo.getSelectedIndex()!=0){
            // TODO add your handling code here:
            Statement sentencia = dameConexion().createStatement();
            if(jTextFieldIp.getText().isEmpty()&&jTextFieldMac.getText().isEmpty()){
             String sql="INSERT INTO Dispositivo (id_dispositivo, modelo, id_marca, numero_serie, ean13, id_tipo) VALUES("+jTextFieldIdDispositivo.getText()+", '"+jTextFieldModelo.getText()+"', '"+idmarca.get(jComboBoxMarca.getItemAt(jComboBoxMarca.getSelectedIndex()))+"', '"+jTextFieldNumeroDeSerie.getText()+"', '"+jFormattedTextFieldean13.getText()+"', '"+idtipo.get(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()))+"')";
           // System.out.println(sql); 
            sentencia.executeUpdate(sql);
            }else if(jTextFieldIp.getText().isEmpty()||jTextFieldMac.getText().isEmpty()){
                if(jTextFieldIp.getText().isEmpty()){
                     String sql="INSERT INTO Dispositivo (id_dispositivo, modelo, id_marca, numero_serie, ean13, id_tipo, ip) VALUES("+jTextFieldIdDispositivo.getText()+", '"+jTextFieldModelo.getText()+"', '"+idmarca.get(jComboBoxMarca.getItemAt(jComboBoxMarca.getSelectedIndex()))+"', '"+jTextFieldNumeroDeSerie.getText()+"', '"+jFormattedTextFieldean13.getText()+"', '"+idtipo.get(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()))+"', '"+jTextFieldIp.getText()+"')";
                     //System.out.println(sql);
                     sentencia.executeUpdate(sql);
                }else if(jTextFieldMac.getText().isEmpty()){
                     String sql="INSERT INTO Dispositivo (id_dispositivo, modelo, id_marca, numero_serie, ean13, id_tipo, mac) VALUES("+jTextFieldIdDispositivo.getText()+", '"+jTextFieldModelo.getText()+"', '"+idmarca.get(jComboBoxMarca.getItemAt(jComboBoxMarca.getSelectedIndex()))+"', '"+jTextFieldNumeroDeSerie.getText()+"', '"+jFormattedTextFieldean13.getText()+"', '"+idtipo.get(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()))+"', '"+jTextFieldMac.getText()+"')";
                     //System.out.println(sql);
                     sentencia.executeUpdate(sql);
                }
            }else{
            String sql="INSERT INTO Dispositivo (id_dispositivo, modelo, id_marca, numero_serie, ean13, id_tipo, ip, mac) VALUES("+jTextFieldIdDispositivo.getText()+", '"+jTextFieldModelo.getText()+"', '"+jComboBoxMarca.getItemAt(jComboBoxMarca.getSelectedIndex())+"', '"+jTextFieldNumeroDeSerie.getText()+"', '"+jFormattedTextFieldean13.getText()+"', '"+jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex())+"', '"+jTextFieldIp.getText()+"', '"+jTextFieldMac.getText()+"')";
                  //System.out.println(sql);
            sentencia.executeUpdate(sql);
            }
             }else{
                 JOptionPane.showMessageDialog(this, "Los campos con * son obligatorios");
             }
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this,"Has insertado datos incorrectos");
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
             JOptionPane.showMessageDialog(this,"Ha ocurrido un problema");
        }
    }//GEN-LAST:event_jButtonDispositivosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AcercaDe v1 = new AcercaDe();
        v1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Aniadir v1 = new Aniadir();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        AniadirMarca jD1 = new AniadirMarca(this,true);
        jD1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        AniadirTipoDispositivo jD1 = new AniadirTipoDispositivo(this,true);
        jD1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonasignar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonasignar1ActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(jComboBoxIdPuestoUsuario.getSelectedIndex()!=0&&jComboBoxIdUsuario.getSelectedIndex()!=0){
                Statement sentencia = dameConexion().createStatement();
                String sql="INSERT INTO Usuario_Puesto (id_usuario,id_puesto) VALUES ("+idusuario.get(jComboBoxIdUsuario.getItemAt(jComboBoxIdUsuario.getSelectedIndex()))+", "+jComboBoxIdPuestoUsuario.getItemAt(jComboBoxIdPuestoUsuario.getSelectedIndex())+")";
                //System.out.println(sql); 
                sentencia.executeUpdate(sql);
            }else if(jComboBoxIdPuestoUsuario.getSelectedIndex()==0&&jComboBoxIdUsuario.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar un usuario y un puesto vacio.");
            }else if(jComboBoxIdPuestoUsuario.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar un puesto vacio si no hay es que no hay puestos vacios.");
            }else if(jComboBoxIdUsuario.getSelectedIndex()==0){
                JOptionPane.showMessageDialog(this, "Tienes que seleccionar un usuario para el puesto.");
            }
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
            JOptionPane.showMessageDialog(this,"Has insertado datos incorrectos");
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
             JOptionPane.showMessageDialog(this,"Ha ocurrido un problema");
        }
    }//GEN-LAST:event_jButtonasignar1ActionPerformed

    private void jFormattedTextFieldean13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldean13KeyReleased
        // TODO add your handling code here:
        String ean13 = jFormattedTextFieldean13.getText();
        char[] cadena = ean13.toCharArray();
        String  caracter = String.valueOf(cadena[cadena.length-1]);
        String[] numeros={"1","2","3","4","5","6","7","8","9","0"};
        boolean comprobador=false;
        for(int i=0;i<numeros.length;i++)
        {
           if(caracter.equals(numeros[i]))
           {
               comprobador=true;
               i=numeros.length;
           }
        }
        if(!comprobador){
           ean13=String.valueOf(cadena);
           ean13=ean13.replaceFirst(".$", "");
        }
        if(cadena.length==13)
        {
            if(!validadorEan13(ean13)){
                JOptionPane.showMessageDialog(this,"Eso no es un ean13 correcto");
                ean13="";
            }
        }
        jFormattedTextFieldean13.setText(ean13);
    }//GEN-LAST:event_jFormattedTextFieldean13KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
                
                    javax.swing.UIManager.setLookAndFeel(new NoireLookAndFeel());
                    
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aniadir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDispositivos;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JButton jButtonaniadirPuesto;
    private javax.swing.JButton jButtonasignar;
    private javax.swing.JButton jButtonasignar1;
    private javax.swing.JComboBox<String> jComboBoxIdDispositivo;
    private javax.swing.JComboBox<String> jComboBoxIdPuesto;
    private javax.swing.JComboBox<String> jComboBoxIdPuestoUsuario;
    private javax.swing.JComboBox<String> jComboBoxIdUsuario;
    private javax.swing.JComboBox<String> jComboBoxMarca;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JTextField jFormattedTextFieldean13;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAniadirPlanta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField jTextFieldApellido1;
    private javax.swing.JTextField jTextFieldApellido2;
    private javax.swing.JTextField jTextFieldIdDispositivo;
    private javax.swing.JTextField jTextFieldIdPuesto1;
    private javax.swing.JTextField jTextFieldIp;
    private javax.swing.JTextField jTextFieldMac;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNumeroDeSerie;
    private javax.swing.JTextField jTextFieldPlanta1;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
