/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package tfc;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.logging.ConsoleHandler;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author terak
 */
public class EliminarPuesto extends javax.swing.JDialog {

    /**
     * Creates new form EliminarPuesto
     */
    public EliminarPuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Statement sentencia;
        try {
            sentencia = dameConexion().createStatement();
        
            String sql="SELECT id_puesto FROM Puesto";
            ResultSet resul = sentencia.executeQuery(sql);
            while(resul.next())
            {
                jComboBox1.addItem(resul.getString(1));
            }
            } catch (SQLException ex) {
              log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        
    }
 private FileHandler fileHandler;
 private ConsoleHandler cons;
 private Logger log = Logger.getLogger("controlador");
 private void logs(){
    try {
            cons = new ConsoleHandler();
            log.addHandler(cons);
            fileHandler = new FileHandler("Logs/errorres.log", true);
            fileHandler.setFormatter(new SimpleFormatter());
            log.addHandler(fileHandler);
        } catch (IOException e) {
            e.printStackTrace();
            log.severe("Ocurrió un error: " + e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Elegir puesto a borrar--" }));

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(69, 69, 69)
                        .addComponent(jButton2))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private Connection dameConexion(){
        Connection con = null;
        String baseDatos = "jdbc:sqlite:"+System.getProperty("user.dir")+"\\BBDD\\BBDD.db";
        /*File f = new File(System.getProperty("user.dir")+"\\BBDD\\BBDD.db");
        System.out.println(f.exists());*/
        try {
            con= DriverManager.getConnection(baseDatos);
        } catch (SQLException ex) {
              log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        
        return con;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int resul = JOptionPane.showConfirmDialog(this, "¿Desea eliminar el dispositivo de la base de datos? (Tenga en cuenta que se pondra predefinido el primer registro) ");
        //System.out.println(resul);
        if(resul==0){
            Connection con= dameConexion();
            try {
                Statement sentencia = con.createStatement();
                String idPuesto;
                ResultSet result = sentencia.executeQuery("SELECT id_puesto FROM Usuario_Puesto WHERE id_puesto = "+jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
                result.next();
                idPuesto=result.getString(1);
                if(idPuesto == null){
                String id="DELETE FROM Usuario_Puesto WHERE id_puesto = "+jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
                  sentencia.executeUpdate(id);
                }

                
                String sql="DELETE FROM Puesto WHERE id_puesto = "+jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
                sentencia.executeUpdate(sql);
            } catch (SQLException ex) {
                  log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarPuesto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EliminarPuesto dialog = new EliminarPuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    // End of variables declaration//GEN-END:variables
}
