
package tfc;

import com.jtattoo.plaf.noire.NoireLookAndFeel;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.logging.FileHandler;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.SimpleFormatter;
import javax.swing.table.DefaultTableModel;
import java.util.logging.ConsoleHandler;
/**
 *
 * @author tarek
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
   
    
    public VentanaPrincipal(){
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setResizable(true);
        logs();
        jButtonLimpiar.setVisible(false);
        Object[] cabecera = new Object[]{"Id Dispositivo","Tipo de Dispositivo","Usuario","Id Puesto","Planta"};
        Object[][] datos = new Object[][]{};
        DefaultTableModel miModelo = new DefaultTableModel(datos,cabecera){
        @Override
        public Class getColumnClass(int columnIndex){
        switch(columnIndex){
            case 0,3,4: return Integer.class;
            default: return Object.class;
        }
        }
        };
        jTable.setModel(miModelo);
        try {
            Statement sentencia = dameConexion().createStatement();
            String sql="SELECT U.usuario, P.id_puesto, P.planta, D.id_dispositivo, T.tipo, T.id_tipo FROM Usuario U, Puesto P, Dispositivo D, Puesto_Dispositivo PD, Tipo T, Usuario_Puesto UP WHERE U.id_usuario = UP.id_usuario AND UP.id_puesto = P.id_puesto AND P.id_puesto = PD.id_puesto AND PD.id_dispositivo = D.id_dispositivo AND D.id_tipo = T.id_tipo;";
            ResultSet resul = sentencia.executeQuery(sql);
            Object[] resultado = {"","","","",""};
            while(resul.next())
            {
                resultado[2]=resul.getString(1);
                resultado[3]=resul.getInt(2);
                resultado[4]=resul.getInt(3);
                resultado[0]=resul.getInt(4);
                resultado[1]=resul.getString(5);
               
                miModelo.addRow(resultado);
            }
            
            String sql2="SELECT id_tipo, tipo FROM Tipo";
            
            resul = sentencia.executeQuery(sql2);
            while(resul.next())
            {
                jComboBoxTipo.addItem(resul.getString(2));
                idtipo.put(resul.getString(2), resul.getInt(1));
            }
            
            
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        
    }
    private FileHandler fileHandler;
    private ConsoleHandler cons;
    private Logger log = Logger.getLogger("controlador");
    private void logs(){
    try {
            cons = new ConsoleHandler();
            log.addHandler(cons);
            fileHandler = new FileHandler("Logs/errorres.log", true);
            fileHandler.setFormatter(new SimpleFormatter());
            log.addHandler(fileHandler);
        } catch (IOException e) {
            e.printStackTrace();
            log.severe("Ocurrió un error: " + e.getMessage());
        }
    }
    private HashMap<String, Integer> idtipo = new HashMap<String, Integer>();
    private Connection dameConexion(){
        Connection con = null;
        String baseDatos = "jdbc:sqlite:"+System.getProperty("user.dir")+"\\BBDD\\BBDD.db";
       
        try {
            con= DriverManager.getConnection(baseDatos);
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        return con;
    }
       /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jTextFieldPuesto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldPlanta = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDispositivo = new javax.swing.JTextField();
        jButtonFiltrar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAniadirPlanta = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar/Modificar"));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Usuario");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 6, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.insets = new java.awt.Insets(28, 270, 0, 0);
        jPanel2.add(jTextFieldUsuario, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 270, 0, 0);
        jPanel2.add(jTextFieldPuesto, gridBagConstraints);

        jLabel3.setText("Puesto");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 6, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Planta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        jPanel2.add(jLabel4, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 270, 52, 0);
        jPanel2.add(jTextFieldPlanta, gridBagConstraints);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona el tipo de dispositivo" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        gridBagConstraints.insets = new java.awt.Insets(1, 67, 0, 240);
        jPanel2.add(jComboBoxTipo, gridBagConstraints);

        jLabel1.setText("Id Dispositivo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 6, 0, 0);
        jPanel2.add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 67, 52, 0);
        jPanel2.add(jTextFieldDispositivo, gridBagConstraints);

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        jPanel2.add(jButtonFiltrar, gridBagConstraints);

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 8, 0);
        jPanel2.add(jButtonLimpiar, gridBagConstraints);

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1281, Short.MAX_VALUE)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Logo.jpg"))); // NOI18N
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setText("Secciones");

        jMenuItem2.setText("Ventana Principal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuItem3.setText("Usuarios");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Dispositivos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Añadir");

        jMenuItemAniadirPlanta.setText("Añadir");
        jMenuItemAniadirPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAniadirPlantaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAniadirPlanta);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Info");

        jMenuItem1.setText("Acerca De");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        Usuarios v1 = new Usuarios();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal v1 = new VentanaPrincipal();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal v1 = new VentanaPrincipal();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        Dispositivos v1 = new Dispositivos();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItemAniadirPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAniadirPlantaActionPerformed
        // TODO add your handling code here:
        Aniadir v1 = new Aniadir();
        v1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemAniadirPlantaActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
        // TODO add your handling code here:
        jButtonLimpiar.setVisible(true);
        Object[] cabecera = new Object[]{"Id Dispositivo","Tipo de Dispositivo","Usuario","Id Puesto","Planta"};
        Object[][] datos = new Object[][]{};
        DefaultTableModel miModelo = new DefaultTableModel(datos,cabecera){
        @Override
        public Class getColumnClass(int columnIndex){
        switch(columnIndex){
            case 0,3,4: return Integer.class;
            default: return Object.class;
        }
        }
        };
        jTable.setModel(miModelo);
        try {
            Statement sentencia = dameConexion().createStatement();
            String sql="SELECT U.usuario, P.id_puesto, P.planta, D.id_dispositivo, T.tipo, T.id_tipo FROM Usuario U, Puesto P, Dispositivo D, Puesto_Dispositivo PD, Tipo T, Usuario_Puesto UP WHERE U.id_usuario = UP.id_usuario AND UP.id_puesto = P.id_puesto AND P.id_puesto = PD.id_puesto AND PD.id_dispositivo = D.id_dispositivo AND D.id_tipo = T.id_tipo ";
            if(!jTextFieldUsuario.getText().isEmpty()){
                sql=sql+"AND U.usuario LIKE '%"+jTextFieldUsuario.getText()+"%'";
                
            }
            if(jComboBoxTipo.getSelectedIndex()!=0){
                
                sql=sql+"AND T.id_tipo LIKE '"+idtipo.get(jComboBoxTipo.getItemAt(jComboBoxTipo.getSelectedIndex()))+"'";
                
                
            }
            if(!jTextFieldDispositivo.getText().isEmpty()){
                sql=sql+"AND D.id_dispositivo LIKE '%"+jTextFieldDispositivo.getText()+"%'";
                
            }
            if(!jTextFieldPuesto.getText().isEmpty()){
                sql=sql+"AND P.id_puesto LIKE '%"+jTextFieldPuesto.getText()+"%'";
                
            }
            if(!jTextFieldPlanta.getText().isEmpty()){
                sql=sql+"AND P.planta LIKE '%"+jTextFieldPlanta.getText()+"%'";
                
            }
            
            ResultSet resul = sentencia.executeQuery(sql);
            Object[] resultado = {"","","","",""};
            
            
            while(resul.next())
            {
                
        
                
                 resultado[2]=resul.getString(1);
                resultado[3]=resul.getInt(2);
                resultado[4]=resul.getInt(3);
                resultado[0]=resul.getInt(4);
                resultado[1]=resul.getString(5);
                jComboBoxTipo.addItem(resul.getString(5));
                
                  miModelo.addRow(resultado);
            }
           
            System.out.println();
            
        } catch (SQLException ex) {
            log.severe("Ocurrió un error: " + ex.getMessage());
             Logger.getLogger(VentanaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
        
        jTextFieldUsuario.setText("");
        jTextFieldPuesto.setText("");
        jTextFieldPlanta.setText("");
        jComboBoxTipo.setSelectedIndex(1);
        jTextFieldDispositivo.setText("");
        Object[] cabecera = new Object[]{"Id Dispositivo","Tipo de Dispositivo","Usuario","Id Puesto","Planta"};
        Object[][] datos = new Object[][]{};
        DefaultTableModel miModelo = new DefaultTableModel(datos,cabecera){
        @Override
        public Class getColumnClass(int columnIndex){
        switch(columnIndex){
            case 0,3,4: return Integer.class;
            default: return Object.class;
        }
        }
        };
        jTable.setModel(miModelo);
        try {
            Statement sentencia = dameConexion().createStatement();
            String sql="SELECT U.usuario, P.id_puesto, P.planta, D.id_dispositivo, T.tipo, T.id_tipo FROM Usuario U, Puesto P, Dispositivo D, Puesto_Dispositivo PD, Tipo T, Usuario_Puesto UP WHERE U.id_usuario = UP.id_usuario AND UP.id_puesto = P.id_puesto AND P.id_puesto = PD.id_puesto AND PD.id_dispositivo = D.id_dispositivo AND D.id_tipo = T.id_tipo;";
            ResultSet resul = sentencia.executeQuery(sql);
            Object[] resultado = {"","","","",""};
            while(resul.next())
            {
                resultado[2]=resul.getString(1);
                resultado[3]=resul.getInt(2);
                resultado[4]=resul.getInt(3);
                resultado[0]=resul.getInt(4);
                resultado[1]=resul.getString(5);
               
                miModelo.addRow(resultado);
            }
            
            String sql2="SELECT id_tipo, tipo FROM Tipo";
            
            resul = sentencia.executeQuery(sql2);
            while(resul.next())
            {
                jComboBoxTipo.addItem(resul.getString(2));
                idtipo.put(resul.getString(2), resul.getInt(1));
            }
            
            
            
        } catch (SQLException ex) {
             log.severe("Ocurrió un error: " + ex.getMessage());
        }catch(Exception e){
            log.severe("Ocurrió un error: " + e.getMessage());
        }
        jTextFieldUsuario.setText("");
        jTextFieldPuesto.setText("");
        jTextFieldPlanta.setText("");
        jTextFieldDispositivo.setText("");
        jComboBoxTipo.setSelectedIndex(0);
        jButtonLimpiar.setVisible(false);
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTableMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AcercaDe v1 = new AcercaDe();
        v1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            
                
                    javax.swing.UIManager.setLookAndFeel(new NoireLookAndFeel());
                    
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAniadirPlanta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDispositivo;
    private javax.swing.JTextField jTextFieldPlanta;
    private javax.swing.JTextField jTextFieldPuesto;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
